### ISSUE TITLE
Maintain queue operation in the master-replica scheme

### ISSUE THREAD

**Issue by 0x501D** [tarantool/go-tarantool#179]
Queue can be setup to work in a [master-replica scheme](https://github.com/tarantool/queue#queue-and-replication)
To work with this scheme from go-tarantool, we need to solve the following tasks:
- [x] tarantool/go-tarantool#176
- [x] tarantool/go-tarantool#177
- [x] tarantool/go-tarantool#178
